git:
  depth: false
language: rust
rust:
  - nightly
before_script:
  - rustup component add clippy rustfmt
  - cd fft
  - apt install libopencv-dev
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test